name: PlainKate
favicon: null
layout_spectrum: 0.12780963815748692
typography_spectrum: 0.49173919088207185
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.02371374052017927
  lightness: 0.7323716101236641
  saturation: 0.03005886566825211
  rhythmicContrast: 0.13865391281433403
purpose: []
